Repository membraneframework/membrane_core, pull requests merged in 2022-04, with the labels that each got.

#416 RemoteStream - atoms formatting
  lib/membrane/remote_stream.ex
Labels: docs, no-changelog

#405 Reliable unlinking/case 2
  lib/membrane/core/bin/pad_controller.ex
  lib/membrane/core/child/lifecycle_controller.ex
  lib/membrane/core/element/lifecycle_controller.ex
  lib/membrane/core/element/pad_controller.ex
  lib/membrane/core/parent/child_life_controller.ex
  lib/membrane/core/parent/child_life_controller/link_handler.ex
  lib/membrane/core/parent/lifecycle_controller.ex
  test/membrane/integration/linking_test.exs
Labels: no-changelog

#422 Revoke `:elements` key in Membrane.Testing.Pipeline.Options struct
  lib/membrane/parent_spec.ex
  lib/membrane/testing/pipeline.ex
Labels: no-changelog

#423 Release membrane_core v0.10.0
  README.md
  mix.exs
  mix.lock
Labels: no-changelog

#424 Temporairly disable error on unlinking static pads due to possible RC
  lib/membrane/core/element/pad_controller.ex
  test/membrane/integration/linking_test.exs
Labels: enhancement, no-changelog
