Repository membraneframework/membrane_core, pull requests merged in 2022-11, with the labels that each got.

#467 only configure junit in test env
  config/config.exs
Labels: no-changelog

#466 Remove :type from def_options
  CHANGELOG.md
  lib/membrane/core/options_specs.ex
  lib/membrane/testing/endpoint.ex
  lib/membrane/testing/sink.ex
  lib/membrane/time.ex
  test/membrane/element_test.exs
  test/support/bin/test_bins.ex
  test/support/child_removal_test/filter.ex
  test/support/demands_test/filter.ex
  test/support/sync/source.ex
Labels: enhancement, breaking-change

#470 Remove @list_test from Membrane.Pad
  lib/membrane/pad.ex
  mix.exs
  mix.lock
Labels: bug, no-changelog

#469 Create a doc describing changes in 0.11
  guides/upgrading/v0.11.md
  mix.exs
Labels: docs, no-changelog

#473 Implement unregistering resources in ResourceGuard
  lib/membrane/core/bin.ex
  lib/membrane/core/element.ex
  lib/membrane/core/pipeline.ex
  lib/membrane/resource_guard.ex
  test/membrane/resource_guard_test.exs
Labels: enhancement, no-changelog

#476 Fix bunch config parser warnings
  lib/membrane/core/child/pads_specs.ex
  lib/membrane/core/element/pad_controller.ex
  lib/membrane/filter_aggregator.ex
  mix.exs
  mix.lock
  test/membrane/core/element_test.exs
  test/membrane/filter_aggregator/integration_test.exs
  test/membrane/integration/links_validation_test.exs
  test/support/accepted_format_test/inner_sink_bin.ex
  test/support/accepted_format_test/outer_sink_bin.ex
  test/support/accepted_format_test/restrictive_sink.ex
  test/support/accepted_format_test/restrictive_source.ex
  test/support/accepted_format_test/sink.ex
  test/support/accepted_format_test/source.ex
  test/support/bin/test_bins.ex
Labels: no-changelog

#472 add playback related changes to the release guide
  guides/upgrading/v0.11.md
  lib/membrane/pipeline.ex
Labels: no-changelog

#475 Put in guide info about updating tuples returned from callbacks
  guides/upgrading/v0.11.md
Labels: docs, no-changelog

#477 Implement running all cleanup functions in ResourceGuard
  lib/membrane/resource_guard.ex
  test/membrane/core/pipeline_test.exs
  test/membrane/integration/child_spawn_test.exs
  test/membrane/integration/linking_test.exs
Labels: enhancement, no-changelog

#474 Updating guide - parent/children communication and childrenspecs
  guides/upgrading/v0.11.md
  lib/membrane/pipeline.ex
  mix.exs
  mix.lock
Labels: no-changelog

#481 Fix typo
  test/membrane/integration/accepted_format_test.exs
Labels: no-changelog
