Repository membraneframework/membrane_core, pull requests merged in 2022-12, with the labels that each got.

#438 Bump Ratio to 3.0
  lib/membrane/clock.ex
  lib/membrane/core/timer.ex
  lib/membrane/time.ex
  mix.exs
  mix.lock
  test/membrane/clock_test.exs
  test/membrane/core/element_test.exs
Labels: no-changelog

#485 Add :handle_tick implementation to the Zombie modules
  lib/membrane/core/parent/lifecycle_controller.ex
  lib/membrane/core/timer_controller.ex
Labels: bug, enhancement, no-changelog

#490 Fix pad docs generation
  lib/membrane/core/child/pads_specs.ex
  lib/membrane/core/element/demand_handler.ex
Labels: no-changelog

#488 fix subprocess supervisor crash when a child fails in handle_init
  lib/membrane/core/subprocess_supervisor.ex
Labels: no-changelog

#495 Remove credo supress
  lib/membrane/pipeline.ex
Labels: enhancement, no-changelog

#494 Update Membrane.Time API
  CHANGELOG.md
  lib/membrane/core/timer.ex
  lib/membrane/sync.ex
  lib/membrane/time.ex
  test/membrane/time_test.exs
Labels: enhancement
