Repository membraneframework/membrane_core, pull requests merged in 2022-01, with the labels that each got.

#380 Update value returned by handle_init/1 in Membrane.Element.Base
  lib/membrane/element/base.ex
Labels: bug, no-changelog

#381 Add link to the membrane tutorials in readme
  README.md
Labels: no-changelog

#383 Remove generation of default .epub docs
  mix.exs
Labels: docs, no-changelog

#382 Endpoint
  CHANGELOG.md
  lib/membrane/core/element.ex
  lib/membrane/core/element/action_handler.ex
  lib/membrane/core/element/buffer_controller.ex
  lib/membrane/core/element/demand_handler.ex
  lib/membrane/element.ex
  lib/membrane/element/action.ex
  lib/membrane/element/base.ex
  lib/membrane/element/callback_context/write.ex
  lib/membrane/element/with_input_pads.ex
  lib/membrane/element/with_output_pads.ex
  lib/membrane/endpoint.ex
  lib/membrane/pad.ex
  lib/membrane/testing/endpoint.ex
  mix.exs
  test/membrane/integration/endpoint_test.exs
  test/membrane/testing/endpoint_test.exs
Labels: enhancement
