Repository membraneframework/membrane_core, pull requests merged in 2023-01, with the labels that each got.

#497 Write function to get child pid in tests
  CHANGELOG.md
  lib/membrane/core/bin.ex
  lib/membrane/core/element.ex
  lib/membrane/core/pipeline.ex
  lib/membrane/testing/pipeline.ex
  test/membrane/testing/pipeline_test.exs
Labels: enhancement

#496 Remove :playback action
  CHANGELOG.md
  lib/membrane/bin/action.ex
  lib/membrane/core/bin/action_handler.ex
  lib/membrane/core/bin/state.ex
  lib/membrane/core/element/action_handler.ex
  lib/membrane/core/element/lifecycle_controller.ex
  lib/membrane/core/element/state.ex
  lib/membrane/core/lifecycle_controller.ex
  lib/membrane/core/parent/child_life_controller.ex
  lib/membrane/core/parent/child_life_controller/link_utils.ex
  lib/membrane/core/parent/lifecycle_controller.ex
  lib/membrane/core/pipeline/action_handler.ex
  lib/membrane/core/pipeline/state.ex
  lib/membrane/element/action.ex
  lib/membrane/exceptions.ex
  lib/membrane/pipeline/action.ex
  lib/membrane/playback.ex
  lib/membrane/testing/pipeline.ex
  test/membrane/core/pipeline_test.exs
  test/membrane/integration/bin_test.exs
  test/membrane/integration/child_removal_test.exs
  test/membrane/integration/child_spawn_test.exs
  test/membrane/integration/defer_setup_test.exs
  test/membrane/integration/distributed_pipeline_test.exs
  test/membrane/integration/linking_test.exs
  test/membrane/integration/links_validation_test.exs
  test/membrane/integration/timer_test.exs
  test/membrane/remote_controlled/pipeline_test.exs
  test/membrane/testing/pipeline_test.exs
  test/support/accepted_format_test/restrictive_source.ex
  test/support/accepted_format_test/source.ex
  test/support/bin/test_bins.ex
  test/support/child_crash_test/filter.ex
  test/support/child_crash_test/pipeline.ex
  test/support/child_removal_test/filter_to_be_removed.ex
  test/support/child_removal_test/pipeline.ex
  test/support/demands_test/pipeline.ex
  test/support/log_metadata_test/pipeline.ex
  test/support/sync/pipeline.ex
Labels: enhancement, breaking-change

#499 Unlink only existing children on crash group down
  lib/membrane/core/parent/child_life_controller.ex
Labels: no-changelog

#502 Add `timer_interval_t` to `Element.Action.t`
  lib/membrane/element/action.ex
Labels: no-changelog

#511 Release v1.0.0-rc0 upgrading guide
  guides/upgrading/v1.0.0-rc0.md
  mix.exs
Labels: no-changelog

#516 Fix tests failing on Elixir 1.14
  test/membrane/core/element/action_handler_test.exs
  test/membrane/core/element/pad_model_test.exs
Labels: no-changelog
